# NOTE: update this with your service name
service: cupido-online-backend

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: sa-east-1
  environment:
    userTableName: Users
    messageTableName: Messages
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:sa-east-1:*:*"

functions:
  - ${file(sls/functions/messages/create.yml)}
  - ${file(sls/functions/messages/delete.yml)}
  - ${file(sls/functions/messages/list.yml)}

resources:
  - ${file(sls/resources/api-gateway-errors.yml)}